name: Detect Node.js version file

description: Detect Node.js version file

outputs:
  node-version-file:
    description: Detected "node-version-file"
    value: ${{ steps.determine-parameters.outputs.node-version-file }}

runs:
  using: composite
  steps:
    - name: Determine Node.js version parameters
      id: determine-parameters
      run: |
        # Determine Node.js version parameters

        echo "::group::Determine Node.js version parameters"

        echo "Attempting to detect Node.js version file"
        if [[ -e .nvmrc ]]; then
          node_version_file=.nvmrc
        elif [[ -e .node-version ]]; then
          node_version_file=.node-version
        elif [[ -e package.json && $( jq -r .volta.node < package.json ) != "null" ]]; then
          node_version_file=package.json
        else
          echo "No Node.js version file detected"
        fi

        echo "Result:"

        echo node-version-file=$node_version_file | tee -a "$GITHUB_OUTPUT"

        echo "::endgroup::"
      shell: bash
