name: Actionlint

on:
  workflow_call:
    inputs:
      runs-on:
        required: false
        type: string
        default: ubuntu-latest

jobs:
  actionlint:
    runs-on: ${{ inputs.runs-on }}
    steps:
      - name: Checkout the source
        uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac # v4.0.0
        with:
          show-progress: false
          # There is little chance that the action is in a submodule.
          submodules: false

      - name: Download latest actionlint
        id: get_actionlint
        run: bash <(curl https://raw.githubusercontent.com/rhysd/actionlint/main/scripts/download-actionlint.bash)

      - name: Check workflow files
        run: ${{ steps.get_actionlint.outputs.executable }} -color
