name: Node.js pnpm build, lint and test

on:
  workflow_call:
    inputs:
      build:
        description: whether it builds your code
        default: true
        required: false
        type: boolean
      lint:
        description: whether it lints your code
        default: true
        required: false
        type: boolean
      test:
        description: whether it tests your code
        default: true
        required: false
        type: boolean
      os:
        default: '[ "ubuntu-latest", "windows-latest" ]'
        required: false
        type: string
      node-versions:
        default: '[ 14, 16, 18, 19 ]'
        required: false
        type: string

jobs:
  build-test:
    name: Build, Lint and Test
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: ${{ fromJson(inputs.os) }}
        node-version: ${{ fromJson(inputs.node-versions) }}

    steps:
      - name: Checkout the source
        uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8 # tag=v3.1.0

      - name: Setup pnpm
        uses: pnpm/action-setup@c3b53f6a16e57305370b4ae5a540c2077a1d50dd # tag=v2.2.4

      - name: Setup Node.js ${{ matrix.node-version }} on ${{ matrix.os }}
        uses: actions/setup-node@8c91899e586c5b171469028077307d293428b516 # tag=v3.5.1
        with:
          node-version: ${{ matrix.node-version }}
          cache: pnpm

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build
        if: ${{ inputs.build }}
        run: pnpm build

      - name: Lint
        if: ${{ inputs.lint }}
        run: pnpm lint

      - name: Test
        if: ${{ inputs.test }}
        run: pnpm test
