name: Prettier

on:
  workflow_dispatch:
  pull_request:
  push:

jobs:
  prettier:
    name: Prettier
    uses: ./.github/workflows/nodejs-pnpm.yml
    with:
      pnpm-commands: '[ "lint" ]'
      job-title: Check format
      os: '["ubuntu-latest"]'
