name: Prettier

on:
  workflow_dispatch:
  pull_request:
  push:

jobs:
  check-skippable:
    continue-on-error: true
    runs-on: ubuntu-22.04
    outputs:
      skippable: ${{ steps.check.outputs.should_skip }}
    steps:
      - id: check
        uses: fkirc/skip-duplicate-actions@b974a9395958c231af965b70070979a577efa578 # v5.3.2

  lint:
    name: Lint
    needs: check-skippable
    if: needs.check-skippable.outputs.skippable != 'true'
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout the source
        uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4.4.0
        with:
          show-progress: false
          # This checkout is only to get the next action, so no submodule is needed.
          submodules: false

      - uses: ./actions/setup-pnpm-project/

      - run: pnpm lint
